const express = require('express');
const path = require('path');
const fs = require('fs');
const os = require('os');
const { spawn, execSync } = require('child_process');

const router = express.Router();
const ENV_PATH = path.resolve(__dirname, '../../../.env');

function isSetupNeeded() {
  if (process.env.SETUP_COMPLETE === 'true') return false;
  const dataPath = process.env.DATA_PATH || path.join(os.homedir(), 'JobDeck', 'data');
  return !fs.existsSync(path.join(dataPath, 'jd-database.db'));
}

// GET /api/setup/status
router.get('/status', (_req, res) => {
  const home = os.homedir();
  res.json({
    needed: isSetupNeeded(),
    defaults: {
      dataPath:   path.join(home, 'JobDeck', 'data'),
      backupPath: path.join(home, 'JobDeck', 'backups'),
      logPath:    path.join(home, 'JobDeck', 'logs'),
    },
  });
});

// POST /api/setup/complete — writes .env then restarts the process
router.post('/complete', (req, res) => {
  const { dataPath, backupPath, logPath, apiKey, displayName, location, createShortcut } = req.body;
  if (!dataPath) return res.status(400).json({ error: 'dataPath is required' });

  const home = os.homedir();
  const lines = [
    '# JobDeck configuration — generated by setup wizard',
    '',
    `ANTHROPIC_API_KEY=${apiKey || ''}`,
    '',
    `DATA_PATH=${dataPath}`,
    `LOG_PATH=${logPath || path.join(home, 'JobDeck', 'logs')}`,
    `BACKUP_PATH=${backupPath || path.join(home, 'JobDeck', 'backups')}`,
    '',
    `PORT=${process.env.PORT || 3001}`,
    `NODE_ENV=${process.env.NODE_ENV || 'production'}`,
    '',
    'LOW_DISK_WARNING_GB=2',
    'ACCENT_COLOR=#423A8E',
    `DISPLAY_NAME=${displayName || ''}`,
    `SCRAPER_LOCATION=${location || ''}`,
    'SETUP_COMPLETE=true',
  ];

  try {
    fs.writeFileSync(ENV_PATH, lines.join('\n') + '\n');
  } catch (e) {
    return res.status(500).json({ error: 'Failed to write .env: ' + e.message });
  }

  if (createShortcut) {
    try {
      const projectRoot = path.resolve(__dirname, '../../..');
      if (process.platform === 'win32') {
        const batPath  = path.join(projectRoot, 'JobDeck.bat');
        const iconPath = path.join(projectRoot, 'assets', 'icon.ico');
        const shortcut = path.join(os.homedir(), 'Desktop', 'JobDeck.lnk');
        const ps = [
          `$ws = New-Object -ComObject WScript.Shell`,
          `$sc = $ws.CreateShortcut("${shortcut.replace(/\\/g, '\\\\')}")`,
          `$sc.TargetPath = "${batPath.replace(/\\/g, '\\\\')}"`,
          `$sc.WorkingDirectory = "${projectRoot.replace(/\\/g, '\\\\')}"`,
          `$sc.IconLocation = "${iconPath.replace(/\\/g, '\\\\')}"`,
          `$sc.Description = "JobDeck - Job Search Dashboard"`,
          `$sc.Save()`,
        ].join('; ');
        const tmpScript = path.join(os.tmpdir(), 'jd-shortcut.ps1');
        fs.writeFileSync(tmpScript, ps);
        execSync(`powershell -NoProfile -ExecutionPolicy Bypass -File "${tmpScript}"`, { stdio: 'pipe' });
        fs.unlinkSync(tmpScript);
      } else {
        const launcherPath = path.join(projectRoot, 'jobdeck.sh');
        const iconPath     = path.join(projectRoot, 'assets', 'icon.svg');
        const desktopDir   = path.join(os.homedir(), 'Desktop');
        const shortcut     = path.join(desktopDir, 'JobDeck.desktop');
        const desktop = [
          '[Desktop Entry]',
          'Version=1.0',
          'Type=Application',
          'Name=JobDeck',
          'Comment=Job Search Dashboard',
          `Exec=bash "${launcherPath}"`,
          `Icon=${iconPath}`,
          `Path=${projectRoot}`,
          'Terminal=true',
          'Categories=Office;',
        ].join('\n') + '\n';
        fs.mkdirSync(desktopDir, { recursive: true });
        fs.writeFileSync(shortcut, desktop, { mode: 0o755 });
        try { execSync(`gio set "${shortcut}" metadata::trusted true`, { stdio: 'pipe' }); } catch {}
      }
    } catch (e) {
      console.warn('[setup] Could not create desktop shortcut:', e.message);
    }
  }

  res.json({ ok: true, restarting: true });

  // Spawn a fresh process without the old dotenv-injected values so the new
  // .env is loaded cleanly by the child's dotenv.config({ override: true }).
  const stripKeys = ['DATA_PATH', 'LOG_PATH', 'BACKUP_PATH', 'SETUP_COMPLETE', 'ANTHROPIC_API_KEY', 'DISPLAY_NAME', 'SCRAPER_LOCATION'];
  const childEnv = Object.fromEntries(Object.entries(process.env).filter(([k]) => !stripKeys.includes(k)));

  setTimeout(() => {
    const child = spawn(process.argv[0], process.argv.slice(1), {
      detached: true,
      stdio: 'inherit',
      env: childEnv,
    });
    child.unref();
    process.exit(42);
  }, 300);
});

module.exports = { router, isSetupNeeded };
